# Generated by Django 4.0.4 on 2022-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='main_image',
            field=models.ImageField(default=None, upload_to='gallery'),
        ),
    ]
