# Generated by Django 4.0.4 on 2022-06-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_goods_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
