# Generated by Django 4.0.4 on 2022-06-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_gallery_options_alter_goods_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300, verbose_name='Имя')),
                ('body', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
