# Generated by Django 4.0.4 on 2022-06-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='%d %b %Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
